import Head from 'next/head'; 
import type { ReactNode } from 'react'; 
import { Inter } from 'next/font/google';

import Header from './header';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children
}: {
  children: ReactNode; 
}) {
  return (
    <html lang='en' className='bg-[#EDEBE6] h-full '>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body className={inter.className} style={{margin:"0.75rem", marginTop:"18px", border:"4px solid #000" }}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
